<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CJORDV5" failures="1" tests="5" name="Test" time="46.555" errors="0" timestamp="2023-02-17T11:51:28 EST">
  <testcase classname="tests.LogInTest" name="LogInErrorWithInvalidInputs" time="1.325">
    <failure type="java.lang.AssertionError" message="expected [Please check your username and password. If you still can&amp;apos;t log in, contact your Salesforce administrator.] but found []">
      <![CDATA[java.lang.AssertionError: expected [Please check your username and password. If you still can't log in, contact your Salesforce administrator.] but found []
at tests.LogInTest.LogInErrorWithInvalidInputs(LogInTest.java:160)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LogInErrorWithInvalidInputs -->
  <testcase classname="tests.LogInTest" name="checkRememberMe" time="7.869"/>
  <testcase classname="tests.LogInTest" name="error_logIn" time="1.531"/>
  <testcase classname="tests.LogInTest" name="forgetPasswordTest" time="1.337"/>
  <testcase classname="tests.LogInTest" name="logIn_to_Salesforce" time="4.832"/>
</testsuite> <!-- Test -->
